server.port=8083
spring.application.name=rental-payment-service

spring.mongodb.host=${SPRING_MONGODB_HOST:localhost}
spring.mongodb.port=27017
spring.mongodb.database=vehicle_rental_db

service.api.key=RENTAL-PAYMENT-SECRET-KEY-2026

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs