server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    mongodb:
     
       uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/userdb}


jwt:
  secret: "ChangeThisToALongRandomSecretKeyForJWTSigning123456"
  expiration-ms: 3600000  


services:
  vehicle-service:
    url: ${SERVICES_VEHICLE_SERVICE_URL:http://localhost:8082}
    api-key: VEHICLE_SERVICE_SECRET_KEY_123
  rental-payment-service:
    url: ${SERVICES_RENTAL_PAYMENT_SERVICE_URL:http://localhost:8083}
    api-key: RENTAL-PAYMENT-SECRET-KEY-2026


rate-limit:
  capacity: 20        
  refill-tokens: 20   
  refill-duration-seconds: 60   

cors:
  allowed-origins: "http://localhost:3000,http://localhost:5173,http://localhost:8081"

springdoc:
  swagger-ui:
    path: /swagger-ui.html